Begin PR for README updates
streamingfast/substreams-sink-files pull request #1
Opened 2023-01-11 19:17 UTC by seanmooretechwriter

Opening PR for updates to README file to address the Git task:

https://github.com/streamingfast/substreams/issues/84

2023-01-13 19:31 UTC, seanmooretechwriter commented
Base README in place. Is this adequate or should we add more?

2023-01-16 19:12 UTC, maoueh requested changes

2023-01-16 19:12 UTC, maoueh commented on README.md
> +- Cloned `substreams-sink-files` repository
Those three are not true, Go compiler is not required unless the person wants to compile from source. Rust is also not needed, somehow could run a pre-built `.spkg`. Let's remove those three and `Knowledge of blockchain development`, the other two stays.

2023-01-16 19:12 UTC, maoueh commented on README.md
> +The binary file is installed in your GO_PATH, typically \$HOME/go/bin. Make sure this folder is included in your PATH environment variable.
That is incorrect. It goes in `GOPATH` (and not `GO_PATH`) only when compiling/installing from source directly. When downloading from a pre-built binary, `GOPATH` as no impact at all. This sentence can be removed, I've proposed a small change for the other line.

2023-01-16 19:12 UTC, maoueh commented on README.md
> +Extract `substreams-sink-files` into a folder available in your PATH.
```suggestion
Extract `substreams-sink-files` into a folder and ensure this folder is reference globally via your `PATH` environment variable.
```

2023-01-16 19:12 UTC, maoueh commented on README.md
> +## Using the `substreams-sink-files` tool
Let's update this section with latest content of tutorial, so we talk about output bundles, cursor and other nice thing you have there.

I'm fine also having quicker show up here with links back to the tutorial.

2023-01-16 20:52 UTC, seanmooretechwriter commented on README.md
> +- Cloned `substreams-sink-files` repository
Updated.

2023-01-16 20:52 UTC, seanmooretechwriter commented on README.md
> +The binary file is installed in your GO_PATH, typically \$HOME/go/bin. Make sure this folder is included in your PATH environment variable.
Updated. This was pulled from the file sink KV content written by Steph.

2023-01-16 20:53 UTC, seanmooretechwriter commented on README.md
> +Extract `substreams-sink-files` into a folder available in your PATH.
Updated.

2023-01-16 20:56 UTC, seanmooretechwriter commented on README.md
> +## Using the `substreams-sink-files` tool
I ported the Cursors, Cloud-based storage and Limitations from the tutorial into the README. Is this adequate?

2023-01-23 19:24 UTC, merged